In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/hospital_communication_energy_system.csv")
df

,Timestamp,Patient ID,Temperature (°C),Humidity (%),Oxygen Level (%),Heart Rate (bpm),Blood Pressure (mmHg),Energy Consumption (kWh),Energy Source,Renewable Energy Usage (%),...,Room Humidity (%),HVAC Mode,HVAC Efficiency (%),Outdoor Temperature (°C),Outdoor Humidity (%),Day of the Week,Season,Energy Saving Mode,System Health Check,AI Predicted Health Status
0,01-01-2025 00:00,P0001,35.959197,53.116400,98.863328,76,"(111, 84)",16.747023,Grid,52.755948,...,33.705483,Heating,92.930041,18.903246,58.295437,2,Fall,0,0,Unhealthy
1,01-01-2025 00:05,P0002,36.591216,55.613547,97.408234,98,"(119, 79)",18.816142,Wind,69.839095,...,50.419144,Heating,91.987563,33.844832,50.550620,2,Summer,0,0,Unhealthy
2,01-01-2025 00:10,P0003,36.462011,58.424429,97.106903,93,"(132, 79)",9.902197,Wind,66.295345,...,63.809061,Cooling,88.873706,19.535191,50.933567,2,Fall,1,1,Healthy
3,01-01-2025 00:15,P0004,36.410249,49.649295,96.425162,69,"(120, 75)",9.445146,Grid,77.151743,...,52.816270,Heating,84.876137,24.507892,66.980780,2,Winter,0,1,Healthy
4,01-01-2025 00:20,P0005,36.258128,42.872100,97.484515,78,"(122, 77)",18.928228,Solar,72.641814,...,34.510662,Heating,81.013523,23.751179,43.990726,2,Spring,1,1,Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,04-02-2025 16:55,P9996,36.486313,52.617065,96.935186,60,"(119, 72)",11.576610,Wind,65.883865,...,38.895050,Cooling,93.624983,21.574652,61.082716,1,Spring,0,0,Healthy
9996,04-02-2025 17:00,P9997,37.011693,65.133106,96.742336,96,"(137, 84)",11.340704,Solar,87.100561,...,49.479635,Heating,93.742358,23.188801,55.934743,1,Summer,1,1,Unhealthy
9997,04-02-2025 17:05,P9998,36.407790,54.272084,91.311788,60,"(130, 75)",10.477275,Grid,62.006824,...,48.674210,Cooling,85.684270,24.784233,47.606991,1,Winter,1,0,Unhealthy
9998,04-02-2025 17:10,P9999,36.757020,57.859780,94.570360,78,"(136, 88)",15.390700,Wind,61.532101,...,54.684736,Cooling,83.681221,35.032419,60.851446,1,Summer,1,0,Healthy
9999,04-02-2025 17:15,P10000,37.052674,47.213165,97.319195,90,"(136, 90)",14.656410,Grid,64.682498,...,60.148418,Cooling,87.677778,20.808995,60.748569,1,Summer,1,0,Unhealthy

In [14]:
df['Heart Rate (bpm)'].mean()

np.float64(79.4136)

In [15]:
df['Heart Rate (bpm)'].median()

79.0

In [16]:
df['Heart Rate (bpm)'].mode()

0    60
Name: Heart Rate (bpm), dtype: int64

In [17]:
df['Heart Rate (bpm)'].var()

133.2598610260959

In [18]:
df['Heart Rate (bpm)'].std()

11.543823501167017

In [28]:
data={
  "heartrate":[14,34,23,34,56,14,15,56,60]
}
df1=pd.DataFrame(data)
df1
df1["heartrate"].mode()

0    14
1    34
2    56
Name: heartrate, dtype: int64